import { User } from './user';

export const USERS: User[] = [
  {
    img_url: './assets/images/placeholder.png',
    first_name: 'Krystina',
    last_name: 'McGee',
    birth_date: new Date(954502148000),
    country: 'US',
    status: 'incomplete',
  },
  {
    img_url: './assets/images/placeholder.png',
    first_name: 'Luus',
    last_name: 'Zanetti',
    birth_date: new Date(970399748000),
    country: 'France',
    status: 'incomplete',
  },
  {
    img_url: './assets/images/placeholder.png',
    first_name: 'Denis',
    last_name: 'Abbasi',
    birth_date: new Date(959858948000),
    country: 'South Africa',
    status: 'incomplete',
  },
  {
    img_url: './assets/images/placeholder.png',
    first_name: 'Max',
    last_name: 'Rigby',
    birth_date: new Date(961154948000),
    country: 'Australia',
    status: 'complete',
  },
  {
    img_url: './assets/images/placeholder.png',
    first_name: 'Yaffa',
    last_name: 'Thorton',
    birth_date: new Date(771766148000),
    country: 'Syria',
    status: 'complete',
  },
  {
    img_url: './assets/images/placeholder.png',
    first_name: 'Cairbre',
    last_name: 'Fuhrmann',
    birth_date: new Date(781788548000),
    country: 'Germany',
    status: 'complete',
  },
  {
    img_url: './assets/images/placeholder.png',
    first_name: 'Louis',
    last_name: 'Ljungstrand',
    birth_date: new Date(700226948000),
    country: 'Germany',
    status: 'complete',
  },
  {
    img_url: './assets/images/placeholder.png',
    first_name: 'Ligeia',
    last_name: 'Hudnall',
    birth_date: new Date(832332548000),
    country: 'Scotland',
    status: 'complete',
  },
  {
    img_url: './assets/images/placeholder.png',
    first_name: 'Sylvester',
    last_name: 'Sommer',
    birth_date: new Date(708780548000),
    country: 'US',
    status: 'complete',
  },
  {
    img_url: './assets/images/placeholder.png',
    first_name: 'Michaël',
    last_name: 'Berg',
    birth_date: new Date(842959748000),
    country: 'France',
    status: 'complete',
  },
];
